namespace: devsecops-commerce-qa

resources:
  - ../../base

images:
  - name: ghcr.io/deucesdevops/enterprise-devsecops-eks-platform/frontend
    newTag: 8b1ac5c38bff0d0f125241718324288e1f8a0d1e
  - name: ghcr.io/deucesdevops/enterprise-devsecops-eks-platform/user-service
    newTag: 8b1ac5c38bff0d0f125241718324288e1f8a0d1e
  - name: ghcr.io/deucesdevops/enterprise-devsecops-eks-platform/product-service
    newTag: 8b1ac5c38bff0d0f125241718324288e1f8a0d1e
  - name: ghcr.io/deucesdevops/enterprise-devsecops-eks-platform/order-service
    newTag: 8b1ac5c38bff0d0f125241718324288e1f8a0d1e
  - name: ghcr.io/deucesdevops/enterprise-devsecops-eks-platform/payment-service
    newTag: 8b1ac5c38bff0d0f125241718324288e1f8a0d1e
  - name: ghcr.io/deucesdevops/enterprise-devsecops-eks-platform/notification-service
    newTag: 8b1ac5c38bff0d0f125241718324288e1f8a0d1e

